# Generated by Django 4.2.7 on 2024-04-04 14:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactusdetail',
            name='contactedOn',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
