# Generated by Django 4.2.7 on 2024-04-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactusdetail_contactedon'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactusdetail',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
