# Generated by Django 4.2.2 on 2024-02-22 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomTitle', models.CharField(max_length=50)),
                ('roomDescription', models.CharField(max_length=500)),
                ('roomAddress', models.CharField(max_length=50)),
                ('detailedRoomAddress', models.CharField(max_length=500)),
                ('floor', models.CharField(max_length=50)),
                ('rules', models.CharField(max_length=500)),
                ('numberOfBathroom', models.IntegerField()),
                ('flat', models.CharField(max_length=50)),
                ('parking', models.CharField(max_length=50)),
                ('amenities', models.CharField(max_length=50)),
                ('electricity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('water', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trash', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Room Images')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='room.room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='Room Document')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='room.room')),
            ],
        ),
    ]
