# Generated by Django 4.2.2 on 2024-02-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
