# Generated by Django 4.2.2 on 2024-02-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_room_listed_date_alter_room_amenities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='isAvailable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='isBooked',
            field=models.BooleanField(default=False),
        ),
    ]
