# Generated by Django 4.2.2 on 2024-02-27 19:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room', '0005_book'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='BookRoom',
        ),
    ]
