# Generated by Django 4.2.7 on 2024-03-03 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_alter_bookroom_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookroom',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='room.room'),
        ),
    ]
