# Generated by Django 4.2.7 on 2024-03-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0011_alter_bookroom_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookroom',
            name='moveOutDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
