# Generated by Django 4.2.7 on 2024-03-12 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0014_roomfeedbacks_delete_roomfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityUnitDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electricityPreviousUnit', models.IntegerField(default=0)),
                ('electricityCurrentUnit', models.IntegerField(default=0)),
                ('status', models.CharField(default='Pending update', max_length=50)),
                ('bookedRoom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='room.bookroom')),
            ],
        ),
    ]
