# Generated by Django 4.2.7 on 2024-03-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0015_electricityunitdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookroom',
            name='rentBilledDate',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
