# Generated by Django 4.2.7 on 2024-03-22 07:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0017_bookinglog'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinglog',
            name='bookingDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
