# Generated by Django 4.2.7 on 2024-03-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0019_canceledbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinglog',
            name='status',
            field=models.CharField(default='Cancelled', max_length=50),
        ),
    ]
