# Generated by Django 4.2.7 on 2024-03-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0020_bookinglog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookroom',
            name='status',
            field=models.CharField(default='booked', max_length=50),
        ),
    ]
