# Generated by Django 4.2.7 on 2024-04-03 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0022_remove_bookroom_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ElectricityUnitDetail',
        ),
    ]
