# Generated by Django 4.2.7 on 2024-04-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0027_savedroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookroom',
            name='additionalDetails',
            field=models.TextField(blank=True, null=True),
        ),
    ]
