# Generated by Django 4.2.7 on 2024-04-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0028_bookroom_additionaldetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='isUnderMaintenance',
            field=models.BooleanField(default=False),
        ),
    ]
