# Generated by Django 4.2.7 on 2023-12-27 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userdocument_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useradditionaldetail',
            name='address',
        ),
    ]
