# Generated by Django 4.2.7 on 2024-02-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_usercitizenship_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilepicture',
            name='image',
            field=models.ImageField(default='Profile pictures/User default profile/DefaultUser.png', upload_to='Profile pictures/User profile'),
        ),
    ]
