# Generated by Django 4.2.7 on 2024-03-30 11:05

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_userprofilepicture_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradditionaldetail',
            name='contact_number',
            field=models.CharField(max_length=15),
        ),
    ]
