# Generated by Django 4.2.7 on 2024-03-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_useradditionaldetail_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradditionaldetail',
            name='contact_number',
            field=models.CharField(max_length=15),
        ),
    ]
