# Generated by Django 4.2.7 on 2024-04-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_useradditionaldetail_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradditionaldetail',
            name='has_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
