# Generated by Django 4.2.7 on 2024-03-09 11:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '0014_roomfeedbacks_delete_roomfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amountUpdatedOn', models.DateTimeField(default=django.utils.timezone.now)),
                ('bookedRoom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bookedRoom', to='room.bookroom')),
            ],
        ),
    ]
