# Generated by Django 4.2.7 on 2024-03-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_roombilling'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombilling',
            name='electricityCurrentUnit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roombilling',
            name='electricityPreviousUnit',
            field=models.IntegerField(default=0),
        ),
    ]
