# Generated by Django 4.2.7 on 2024-03-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_roombilling_electricitycurrentunit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombilling',
            name='hasChargeLatePaymentFee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roombilling',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
