# Generated by Django 4.2.7 on 2024-03-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_roombilling_haschargelatepaymentfee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombilling',
            name='electricityAmount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='roombilling',
            name='electricityUnit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='roombilling',
            name='totalRoomRentAmount',
            field=models.IntegerField(default=0),
        ),
    ]
