# Generated by Django 4.2.7 on 2024-03-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_roombilling_electricityamount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombilling',
            name='deposit',
            field=models.IntegerField(default=0),
        ),
    ]
