# Generated by Django 4.2.7 on 2024-03-27 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0022_remove_bookroom_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0006_roombilling_deposit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paidDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('billedDate', models.DateTimeField()),
                ('lateDays', models.IntegerField()),
                ('lateFee', models.IntegerField()),
                ('depositedAmount', models.IntegerField()),
                ('totalPaidAmount', models.IntegerField()),
                ('transactionID', models.CharField(max_length=100)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.room')),
                ('tenantUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
