# Generated by Django 4.2.7 on 2024-03-27 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_paymenthistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyBalance',
        ),
    ]
