# Generated by Django 4.2.7 on 2024-04-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_paymenthistory_hasreleasedfund'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='systemCommissionAmount',
            field=models.IntegerField(default=0),
        ),
    ]
