# Generated by Django 4.2.7 on 2024-05-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_paymenthistory_systemcommissionamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='TrashCharge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='electricityCurrentUnit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='electricityPreviousUnit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='wasChargedLateFee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='waterCharge',
            field=models.IntegerField(default=0),
        ),
    ]
